name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, chalcak_fe]
    name: git clone and deploy

    steps:
      - name: git clone
        run: |
          cd /home/ubuntu/chalcak/front/5-aspyn-community-spring-fe
          git pull

      - name: create .env
        run: |
          cd /home/ubuntu/chalcak/front/5-aspyn-community-spring-fe
          echo "${{ secrets.ENV }}" > .env

      - name: install depency and deploy
        run: |
          cd /home/ubuntu/chalcak/front/5-aspyn-community-spring-fe
          npm install
          pm2 start app.js
